//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discussion.srv {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Participant", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Participant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PseudoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Pseudo {
            get {
                return this.PseudoField;
            }
            set {
                if ((object.ReferenceEquals(this.PseudoField, value) != true)) {
                    this.PseudoField = value;
                    this.RaisePropertyChanged("Pseudo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srv.ws_chatSoap")]
    public interface ws_chatSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément pseudo de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Participer", ReplyAction="*")]
        Discussion.srv.ParticiperResponse Participer(Discussion.srv.ParticiperRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Participer", ReplyAction="*")]
        System.Threading.Tasks.Task<Discussion.srv.ParticiperResponse> ParticiperAsync(Discussion.srv.ParticiperRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément pseudo de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Quiter", ReplyAction="*")]
        Discussion.srv.QuiterResponse Quiter(Discussion.srv.QuiterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Quiter", ReplyAction="*")]
        System.Threading.Tasks.Task<Discussion.srv.QuiterResponse> QuiterAsync(Discussion.srv.QuiterRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément sender de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        Discussion.srv.SendMessageResponse SendMessage(Discussion.srv.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Discussion.srv.SendMessageResponse> SendMessageAsync(Discussion.srv.SendMessageRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément pseudos de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QuiterParticipants", ReplyAction="*")]
        Discussion.srv.QuiterParticipantsResponse QuiterParticipants(Discussion.srv.QuiterParticipantsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QuiterParticipants", ReplyAction="*")]
        System.Threading.Tasks.Task<Discussion.srv.QuiterParticipantsResponse> QuiterParticipantsAsync(Discussion.srv.QuiterParticipantsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClearAll", ReplyAction="*")]
        void ClearAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClearAll", ReplyAction="*")]
        System.Threading.Tasks.Task ClearAllAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParticiperRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Participer", Namespace="http://tempuri.org/", Order=0)]
        public Discussion.srv.ParticiperRequestBody Body;
        
        public ParticiperRequest() {
        }
        
        public ParticiperRequest(Discussion.srv.ParticiperRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ParticiperRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pseudo;
        
        public ParticiperRequestBody() {
        }
        
        public ParticiperRequestBody(string pseudo) {
            this.pseudo = pseudo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParticiperResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ParticiperResponse", Namespace="http://tempuri.org/", Order=0)]
        public Discussion.srv.ParticiperResponseBody Body;
        
        public ParticiperResponse() {
        }
        
        public ParticiperResponse(Discussion.srv.ParticiperResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ParticiperResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Discussion.srv.Participant[] ParticiperResult;
        
        public ParticiperResponseBody() {
        }
        
        public ParticiperResponseBody(Discussion.srv.Participant[] ParticiperResult) {
            this.ParticiperResult = ParticiperResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuiterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Quiter", Namespace="http://tempuri.org/", Order=0)]
        public Discussion.srv.QuiterRequestBody Body;
        
        public QuiterRequest() {
        }
        
        public QuiterRequest(Discussion.srv.QuiterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QuiterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pseudo;
        
        public QuiterRequestBody() {
        }
        
        public QuiterRequestBody(string pseudo) {
            this.pseudo = pseudo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuiterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QuiterResponse", Namespace="http://tempuri.org/", Order=0)]
        public Discussion.srv.QuiterResponseBody Body;
        
        public QuiterResponse() {
        }
        
        public QuiterResponse(Discussion.srv.QuiterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QuiterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Discussion.srv.Participant[] QuiterResult;
        
        public QuiterResponseBody() {
        }
        
        public QuiterResponseBody(Discussion.srv.Participant[] QuiterResult) {
            this.QuiterResult = QuiterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://tempuri.org/", Order=0)]
        public Discussion.srv.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(Discussion.srv.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string texte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Discussion.srv.ArrayOfString recievers;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string sender, string texte, Discussion.srv.ArrayOfString recievers) {
            this.sender = sender;
            this.texte = texte;
            this.recievers = recievers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Discussion.srv.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(Discussion.srv.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendMessageResponseBody {
        
        public SendMessageResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuiterParticipantsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QuiterParticipants", Namespace="http://tempuri.org/", Order=0)]
        public Discussion.srv.QuiterParticipantsRequestBody Body;
        
        public QuiterParticipantsRequest() {
        }
        
        public QuiterParticipantsRequest(Discussion.srv.QuiterParticipantsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QuiterParticipantsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Discussion.srv.ArrayOfString pseudos;
        
        public QuiterParticipantsRequestBody() {
        }
        
        public QuiterParticipantsRequestBody(Discussion.srv.ArrayOfString pseudos) {
            this.pseudos = pseudos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuiterParticipantsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QuiterParticipantsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Discussion.srv.QuiterParticipantsResponseBody Body;
        
        public QuiterParticipantsResponse() {
        }
        
        public QuiterParticipantsResponse(Discussion.srv.QuiterParticipantsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class QuiterParticipantsResponseBody {
        
        public QuiterParticipantsResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ws_chatSoapChannel : Discussion.srv.ws_chatSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ws_chatSoapClient : System.ServiceModel.ClientBase<Discussion.srv.ws_chatSoap>, Discussion.srv.ws_chatSoap {
        
        public ws_chatSoapClient() {
        }
        
        public ws_chatSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ws_chatSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ws_chatSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ws_chatSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion.srv.ParticiperResponse Discussion.srv.ws_chatSoap.Participer(Discussion.srv.ParticiperRequest request) {
            return base.Channel.Participer(request);
        }
        
        public Discussion.srv.Participant[] Participer(string pseudo) {
            Discussion.srv.ParticiperRequest inValue = new Discussion.srv.ParticiperRequest();
            inValue.Body = new Discussion.srv.ParticiperRequestBody();
            inValue.Body.pseudo = pseudo;
            Discussion.srv.ParticiperResponse retVal = ((Discussion.srv.ws_chatSoap)(this)).Participer(inValue);
            return retVal.Body.ParticiperResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Discussion.srv.ParticiperResponse> Discussion.srv.ws_chatSoap.ParticiperAsync(Discussion.srv.ParticiperRequest request) {
            return base.Channel.ParticiperAsync(request);
        }
        
        public System.Threading.Tasks.Task<Discussion.srv.ParticiperResponse> ParticiperAsync(string pseudo) {
            Discussion.srv.ParticiperRequest inValue = new Discussion.srv.ParticiperRequest();
            inValue.Body = new Discussion.srv.ParticiperRequestBody();
            inValue.Body.pseudo = pseudo;
            return ((Discussion.srv.ws_chatSoap)(this)).ParticiperAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion.srv.QuiterResponse Discussion.srv.ws_chatSoap.Quiter(Discussion.srv.QuiterRequest request) {
            return base.Channel.Quiter(request);
        }
        
        public Discussion.srv.Participant[] Quiter(string pseudo) {
            Discussion.srv.QuiterRequest inValue = new Discussion.srv.QuiterRequest();
            inValue.Body = new Discussion.srv.QuiterRequestBody();
            inValue.Body.pseudo = pseudo;
            Discussion.srv.QuiterResponse retVal = ((Discussion.srv.ws_chatSoap)(this)).Quiter(inValue);
            return retVal.Body.QuiterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Discussion.srv.QuiterResponse> Discussion.srv.ws_chatSoap.QuiterAsync(Discussion.srv.QuiterRequest request) {
            return base.Channel.QuiterAsync(request);
        }
        
        public System.Threading.Tasks.Task<Discussion.srv.QuiterResponse> QuiterAsync(string pseudo) {
            Discussion.srv.QuiterRequest inValue = new Discussion.srv.QuiterRequest();
            inValue.Body = new Discussion.srv.QuiterRequestBody();
            inValue.Body.pseudo = pseudo;
            return ((Discussion.srv.ws_chatSoap)(this)).QuiterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion.srv.SendMessageResponse Discussion.srv.ws_chatSoap.SendMessage(Discussion.srv.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public void SendMessage(string sender, string texte, Discussion.srv.ArrayOfString recievers) {
            Discussion.srv.SendMessageRequest inValue = new Discussion.srv.SendMessageRequest();
            inValue.Body = new Discussion.srv.SendMessageRequestBody();
            inValue.Body.sender = sender;
            inValue.Body.texte = texte;
            inValue.Body.recievers = recievers;
            Discussion.srv.SendMessageResponse retVal = ((Discussion.srv.ws_chatSoap)(this)).SendMessage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Discussion.srv.SendMessageResponse> Discussion.srv.ws_chatSoap.SendMessageAsync(Discussion.srv.SendMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Discussion.srv.SendMessageResponse> SendMessageAsync(string sender, string texte, Discussion.srv.ArrayOfString recievers) {
            Discussion.srv.SendMessageRequest inValue = new Discussion.srv.SendMessageRequest();
            inValue.Body = new Discussion.srv.SendMessageRequestBody();
            inValue.Body.sender = sender;
            inValue.Body.texte = texte;
            inValue.Body.recievers = recievers;
            return ((Discussion.srv.ws_chatSoap)(this)).SendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion.srv.QuiterParticipantsResponse Discussion.srv.ws_chatSoap.QuiterParticipants(Discussion.srv.QuiterParticipantsRequest request) {
            return base.Channel.QuiterParticipants(request);
        }
        
        public void QuiterParticipants(Discussion.srv.ArrayOfString pseudos) {
            Discussion.srv.QuiterParticipantsRequest inValue = new Discussion.srv.QuiterParticipantsRequest();
            inValue.Body = new Discussion.srv.QuiterParticipantsRequestBody();
            inValue.Body.pseudos = pseudos;
            Discussion.srv.QuiterParticipantsResponse retVal = ((Discussion.srv.ws_chatSoap)(this)).QuiterParticipants(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Discussion.srv.QuiterParticipantsResponse> Discussion.srv.ws_chatSoap.QuiterParticipantsAsync(Discussion.srv.QuiterParticipantsRequest request) {
            return base.Channel.QuiterParticipantsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Discussion.srv.QuiterParticipantsResponse> QuiterParticipantsAsync(Discussion.srv.ArrayOfString pseudos) {
            Discussion.srv.QuiterParticipantsRequest inValue = new Discussion.srv.QuiterParticipantsRequest();
            inValue.Body = new Discussion.srv.QuiterParticipantsRequestBody();
            inValue.Body.pseudos = pseudos;
            return ((Discussion.srv.ws_chatSoap)(this)).QuiterParticipantsAsync(inValue);
        }
        
        public void ClearAll() {
            base.Channel.ClearAll();
        }
        
        public System.Threading.Tasks.Task ClearAllAsync() {
            return base.Channel.ClearAllAsync();
        }
    }
}
